name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hynek/build-and-inspect-python-package@v1
