name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  release:
    types:
      - published

permissions:
  id-token: write # sigstore

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hynek/build-and-inspect-python-package@v2

      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - uses: actions/upload-artifact@v4
        with:
          name: Packages
          overwrite: true
          path: dist/*
